[package]
name = "pop3"
version = "1.0.6"
authors = ["Matt McCoy <mattnenterprise@yahoo.com>"]
homepage = "https://github.com/mattnenterprise/rust-pop3"
repository = "https://github.com/mattnenterprise/rust-pop3"
description = "POP3 client for Rust"
readme = "README.md"
license = "MIT"
edition = "2018"

[lib]
name = "pop3"
path = "src/pop3.rs"

[[bin]]
name = "example"
path = "example.rs"

[dependencies]
rustls = "0.16.0"
webpki = "0.21.0"
regex = "1.3.1"
lazy_static = "1.4.0"
webpki-roots = "0.18.0"

